# OpenBSD autoinstall configuration for NSWall

System hostname = nswall
Password for root = nswall
Setup a user = nswall
Password for user = nswall
Allow root ssh login = yes
What timezone are you in = UTC
Which disk is the root disk = sd0
Use (W)hole disk MBR, whole disk (G)PT or (E)dit = G
Use (A)uto layout, (E)dit auto layout, or create (C)ustom layout = A
Location of sets = http
HTTP Server = cdn.openbsd.org
Unable to connect using https. Use http instead = yes
Set name(s) = -x* -game* +bsd +bsd.rd +base* +comp* +man*
Directory does not contain SHA256.sig. Continue without verification = yes
Location of sets = done
